apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostservice-deploy
spec:
  selector:
    matchLabels:
      app: hostservice
  template:
    metadata:
      labels:
        app: hostservice
    spec:
      containers:
      - name: hostservice-container
        images: caroline73/hostservice:4bce6f9cca6baae73a9acb8edf825e0c97f335e3
        resources:
          limits:
            memory: "128Mic"
            cpu: "500m"
        ports:
        - containerPort: 8080
